/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppStorageRouteRouteImport } from './routes/_app/storage/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppProjectsRouteRouteImport } from './routes/_app/projects/route'
import { Route as AppDocumentsRouteRouteImport } from './routes/_app/documents/route'
import { Route as AppContactsRouteRouteImport } from './routes/_app/contacts/route'
import { Route as AppStorageIndexRouteImport } from './routes/_app/storage/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting/index'
import { Route as GuestViewTokenRouteImport } from './routes/_guest/view/$token'
import { Route as AppStorageFolderIdRouteImport } from './routes/_app/storage/$folderId'
import { Route as AppSettingsUsageRouteImport } from './routes/_app/settings/usage'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsPrivacyRouteImport } from './routes/_app/settings/privacy'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsLabelsRouteImport } from './routes/_app/settings/labels'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings/integrations'
import { Route as AppSettingsCommunityRouteImport } from './routes/_app/settings/community'
import { Route as AppSettingsBusinessRouteImport } from './routes/_app/settings/business'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings/ai'
import { Route as AppProjectsRecoveryRouteImport } from './routes/_app/projects/recovery'
import { Route as AppDocumentsNewRouteImport } from './routes/_app/documents/new'
import { Route as AppChatSessionIdRouteImport } from './routes/_app/chat/$sessionId'
import { Route as AppAccountingTransactionsRouteImport } from './routes/_app/accounting/transactions'
import { Route as AppAccountingBudgetsRouteImport } from './routes/_app/accounting/budgets'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/_app/projects/$projectId/route'
import { Route as AppDocumentsLibraryRouteRouteImport } from './routes/_app/documents/library/route'
import { Route as AppDocumentsDocumentIdRouteRouteImport } from './routes/_app/documents/$documentId/route'
import { Route as AppContactsContactIdRouteRouteImport } from './routes/_app/contacts/$contactId/route'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppDocumentsLibraryIndexRouteImport } from './routes/_app/documents/library/index'
import { Route as AppDocumentsDocumentIdIndexRouteImport } from './routes/_app/documents/$documentId/index'
import { Route as AppContactsContactIdIndexRouteImport } from './routes/_app/contacts/$contactId/index'
import { Route as AppStorageFolderIdFileIdRouteImport } from './routes/_app/storage/$folderId/$fileId'
import { Route as AppProjectsProjectIdTableRouteImport } from './routes/_app/projects/$projectId/table'
import { Route as AppProjectsProjectIdReportsRouteImport } from './routes/_app/projects/$projectId/reports'
import { Route as AppProjectsProjectIdOverviewRouteImport } from './routes/_app/projects/$projectId/overview'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/_app/projects/$projectId/issues'
import { Route as AppProjectsProjectIdBoardRouteImport } from './routes/_app/projects/$projectId/board'
import { Route as AppDocumentsLibraryTemplatesRouteImport } from './routes/_app/documents/library/templates'
import { Route as AppDocumentsLibraryPackagesRouteImport } from './routes/_app/documents/library/packages'
import { Route as AppDocumentsLibraryBusinessRouteImport } from './routes/_app/documents/library/business'
import { Route as AppDocumentsDocumentIdPromoteRouteImport } from './routes/_app/documents/$documentId/promote'
import { Route as AppDocumentsDocumentIdEditRouteImport } from './routes/_app/documents/$documentId/edit'
import { Route as AppProjectsProjectIdIssuesTaskIdRouteImport } from './routes/_app/projects/$projectId/issues/$taskId'
import { Route as AppProjectsProjectIdBoardTaskIdRouteImport } from './routes/_app/projects/$projectId/board/$taskId'
import { Route as AppProjectsProjectIdStorageFileIdModalRouteImport } from './routes/_app/projects/$projectId/storage/$fileId/modal'
import { Route as AppProjectsProjectIdDocumentsDocumentIdModalRouteImport } from './routes/_app/projects/$projectId/documents/$documentId/modal'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppStorageRouteRoute = AppStorageRouteRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRouteRoute = AppProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRouteRoute = AppDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsRouteRoute = AppContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStorageIndexRoute = AppStorageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStorageRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRouteRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRouteRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRouteRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AppRouteRoute,
} as any)
const GuestViewTokenRoute = GuestViewTokenRouteImport.update({
  id: '/view/$token',
  path: '/view/$token',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AppStorageFolderIdRoute = AppStorageFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => AppStorageRouteRoute,
} as any)
const AppSettingsUsageRoute = AppSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsLabelsRoute = AppSettingsLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsCommunityRoute = AppSettingsCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsBusinessRoute = AppSettingsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppProjectsRecoveryRoute = AppProjectsRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppProjectsRouteRoute,
} as any)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDocumentsRouteRoute,
} as any)
const AppChatSessionIdRoute = AppChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountingTransactionsRoute =
  AppAccountingTransactionsRouteImport.update({
    id: '/accounting/transactions',
    path: '/accounting/transactions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAccountingBudgetsRoute = AppAccountingBudgetsRouteImport.update({
  id: '/accounting/budgets',
  path: '/accounting/budgets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppProjectsRouteRoute,
  } as any)
const AppDocumentsLibraryRouteRoute =
  AppDocumentsLibraryRouteRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AppDocumentsRouteRoute,
  } as any)
const AppDocumentsDocumentIdRouteRoute =
  AppDocumentsDocumentIdRouteRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AppDocumentsRouteRoute,
  } as any)
const AppContactsContactIdRouteRoute =
  AppContactsContactIdRouteRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => AppContactsRouteRoute,
  } as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppDocumentsLibraryIndexRoute =
  AppDocumentsLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDocumentsLibraryRouteRoute,
  } as any)
const AppDocumentsDocumentIdIndexRoute =
  AppDocumentsDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDocumentsDocumentIdRouteRoute,
  } as any)
const AppContactsContactIdIndexRoute =
  AppContactsContactIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppContactsContactIdRouteRoute,
  } as any)
const AppStorageFolderIdFileIdRoute =
  AppStorageFolderIdFileIdRouteImport.update({
    id: '/$fileId',
    path: '/$fileId',
    getParentRoute: () => AppStorageFolderIdRoute,
  } as any)
const AppProjectsProjectIdTableRoute =
  AppProjectsProjectIdTableRouteImport.update({
    id: '/table',
    path: '/table',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdReportsRoute =
  AppProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdOverviewRoute =
  AppProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdBoardRoute =
  AppProjectsProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppDocumentsLibraryTemplatesRoute =
  AppDocumentsLibraryTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppDocumentsLibraryRouteRoute,
  } as any)
const AppDocumentsLibraryPackagesRoute =
  AppDocumentsLibraryPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AppDocumentsLibraryRouteRoute,
  } as any)
const AppDocumentsLibraryBusinessRoute =
  AppDocumentsLibraryBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AppDocumentsLibraryRouteRoute,
  } as any)
const AppDocumentsDocumentIdPromoteRoute =
  AppDocumentsDocumentIdPromoteRouteImport.update({
    id: '/promote',
    path: '/promote',
    getParentRoute: () => AppDocumentsDocumentIdRouteRoute,
  } as any)
const AppDocumentsDocumentIdEditRoute =
  AppDocumentsDocumentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppDocumentsDocumentIdRouteRoute,
  } as any)
const AppProjectsProjectIdIssuesTaskIdRoute =
  AppProjectsProjectIdIssuesTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AppProjectsProjectIdIssuesRoute,
  } as any)
const AppProjectsProjectIdBoardTaskIdRoute =
  AppProjectsProjectIdBoardTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AppProjectsProjectIdBoardRoute,
  } as any)
const AppProjectsProjectIdStorageFileIdModalRoute =
  AppProjectsProjectIdStorageFileIdModalRouteImport.update({
    id: '/storage/$fileId/modal',
    path: '/storage/$fileId/modal',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdDocumentsDocumentIdModalRoute =
  AppProjectsProjectIdDocumentsDocumentIdModalRouteImport.update({
    id: '/documents/$documentId/modal',
    path: '/documents/$documentId/modal',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof AppContactsRouteRouteWithChildren
  '/documents': typeof AppDocumentsRouteRouteWithChildren
  '/projects': typeof AppProjectsRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/storage': typeof AppStorageRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/contacts/$contactId': typeof AppContactsContactIdRouteRouteWithChildren
  '/documents/$documentId': typeof AppDocumentsDocumentIdRouteRouteWithChildren
  '/documents/library': typeof AppDocumentsLibraryRouteRouteWithChildren
  '/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/accounting/budgets': typeof AppAccountingBudgetsRoute
  '/accounting/transactions': typeof AppAccountingTransactionsRoute
  '/chat/$sessionId': typeof AppChatSessionIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/projects/recovery': typeof AppProjectsRecoveryRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/business': typeof AppSettingsBusinessRoute
  '/settings/community': typeof AppSettingsCommunityRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/labels': typeof AppSettingsLabelsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/usage': typeof AppSettingsUsageRoute
  '/storage/$folderId': typeof AppStorageFolderIdRouteWithChildren
  '/view/$token': typeof GuestViewTokenRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/chat/': typeof AppChatIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/storage/': typeof AppStorageIndexRoute
  '/documents/$documentId/edit': typeof AppDocumentsDocumentIdEditRoute
  '/documents/$documentId/promote': typeof AppDocumentsDocumentIdPromoteRoute
  '/documents/library/business': typeof AppDocumentsLibraryBusinessRoute
  '/documents/library/packages': typeof AppDocumentsLibraryPackagesRoute
  '/documents/library/templates': typeof AppDocumentsLibraryTemplatesRoute
  '/projects/$projectId/board': typeof AppProjectsProjectIdBoardRouteWithChildren
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/projects/$projectId/overview': typeof AppProjectsProjectIdOverviewRoute
  '/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
  '/projects/$projectId/table': typeof AppProjectsProjectIdTableRoute
  '/storage/$folderId/$fileId': typeof AppStorageFolderIdFileIdRoute
  '/contacts/$contactId/': typeof AppContactsContactIdIndexRoute
  '/documents/$documentId/': typeof AppDocumentsDocumentIdIndexRoute
  '/documents/library/': typeof AppDocumentsLibraryIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/board/$taskId': typeof AppProjectsProjectIdBoardTaskIdRoute
  '/projects/$projectId/issues/$taskId': typeof AppProjectsProjectIdIssuesTaskIdRoute
  '/projects/$projectId/documents/$documentId/modal': typeof AppProjectsProjectIdDocumentsDocumentIdModalRoute
  '/projects/$projectId/storage/$fileId/modal': typeof AppProjectsProjectIdStorageFileIdModalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/accounting/budgets': typeof AppAccountingBudgetsRoute
  '/accounting/transactions': typeof AppAccountingTransactionsRoute
  '/chat/$sessionId': typeof AppChatSessionIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/projects/recovery': typeof AppProjectsRecoveryRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/business': typeof AppSettingsBusinessRoute
  '/settings/community': typeof AppSettingsCommunityRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/labels': typeof AppSettingsLabelsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/usage': typeof AppSettingsUsageRoute
  '/storage/$folderId': typeof AppStorageFolderIdRouteWithChildren
  '/view/$token': typeof GuestViewTokenRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/chat': typeof AppChatIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/storage': typeof AppStorageIndexRoute
  '/documents/$documentId/edit': typeof AppDocumentsDocumentIdEditRoute
  '/documents/$documentId/promote': typeof AppDocumentsDocumentIdPromoteRoute
  '/documents/library/business': typeof AppDocumentsLibraryBusinessRoute
  '/documents/library/packages': typeof AppDocumentsLibraryPackagesRoute
  '/documents/library/templates': typeof AppDocumentsLibraryTemplatesRoute
  '/projects/$projectId/board': typeof AppProjectsProjectIdBoardRouteWithChildren
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/projects/$projectId/overview': typeof AppProjectsProjectIdOverviewRoute
  '/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
  '/projects/$projectId/table': typeof AppProjectsProjectIdTableRoute
  '/storage/$folderId/$fileId': typeof AppStorageFolderIdFileIdRoute
  '/contacts/$contactId': typeof AppContactsContactIdIndexRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdIndexRoute
  '/documents/library': typeof AppDocumentsLibraryIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/board/$taskId': typeof AppProjectsProjectIdBoardTaskIdRoute
  '/projects/$projectId/issues/$taskId': typeof AppProjectsProjectIdIssuesTaskIdRoute
  '/projects/$projectId/documents/$documentId/modal': typeof AppProjectsProjectIdDocumentsDocumentIdModalRoute
  '/projects/$projectId/storage/$fileId/modal': typeof AppProjectsProjectIdStorageFileIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteRouteWithChildren
  '/_app/documents': typeof AppDocumentsRouteRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/storage': typeof AppStorageRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRouteRouteWithChildren
  '/_app/documents/$documentId': typeof AppDocumentsDocumentIdRouteRouteWithChildren
  '/_app/documents/library': typeof AppDocumentsLibraryRouteRouteWithChildren
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/_app/accounting/budgets': typeof AppAccountingBudgetsRoute
  '/_app/accounting/transactions': typeof AppAccountingTransactionsRoute
  '/_app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/projects/recovery': typeof AppProjectsRecoveryRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/business': typeof AppSettingsBusinessRoute
  '/_app/settings/community': typeof AppSettingsCommunityRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/labels': typeof AppSettingsLabelsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/usage': typeof AppSettingsUsageRoute
  '/_app/storage/$folderId': typeof AppStorageFolderIdRouteWithChildren
  '/_guest/view/$token': typeof GuestViewTokenRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/storage/': typeof AppStorageIndexRoute
  '/_app/documents/$documentId/edit': typeof AppDocumentsDocumentIdEditRoute
  '/_app/documents/$documentId/promote': typeof AppDocumentsDocumentIdPromoteRoute
  '/_app/documents/library/business': typeof AppDocumentsLibraryBusinessRoute
  '/_app/documents/library/packages': typeof AppDocumentsLibraryPackagesRoute
  '/_app/documents/library/templates': typeof AppDocumentsLibraryTemplatesRoute
  '/_app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRouteWithChildren
  '/_app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/_app/projects/$projectId/overview': typeof AppProjectsProjectIdOverviewRoute
  '/_app/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
  '/_app/projects/$projectId/table': typeof AppProjectsProjectIdTableRoute
  '/_app/storage/$folderId/$fileId': typeof AppStorageFolderIdFileIdRoute
  '/_app/contacts/$contactId/': typeof AppContactsContactIdIndexRoute
  '/_app/documents/$documentId/': typeof AppDocumentsDocumentIdIndexRoute
  '/_app/documents/library/': typeof AppDocumentsLibraryIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/board/$taskId': typeof AppProjectsProjectIdBoardTaskIdRoute
  '/_app/projects/$projectId/issues/$taskId': typeof AppProjectsProjectIdIssuesTaskIdRoute
  '/_app/projects/$projectId/documents/$documentId/modal': typeof AppProjectsProjectIdDocumentsDocumentIdModalRoute
  '/_app/projects/$projectId/storage/$fileId/modal': typeof AppProjectsProjectIdStorageFileIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/documents'
    | '/projects'
    | '/settings'
    | '/storage'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/contacts/$contactId'
    | '/documents/$documentId'
    | '/documents/library'
    | '/projects/$projectId'
    | '/accounting/budgets'
    | '/accounting/transactions'
    | '/chat/$sessionId'
    | '/documents/new'
    | '/projects/recovery'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/business'
    | '/settings/community'
    | '/settings/integrations'
    | '/settings/labels'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/usage'
    | '/storage/$folderId'
    | '/view/$token'
    | '/accounting/'
    | '/calendar/'
    | '/chat/'
    | '/contacts/'
    | '/documents/'
    | '/projects/'
    | '/settings/'
    | '/storage/'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/promote'
    | '/documents/library/business'
    | '/documents/library/packages'
    | '/documents/library/templates'
    | '/projects/$projectId/board'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/table'
    | '/storage/$folderId/$fileId'
    | '/contacts/$contactId/'
    | '/documents/$documentId/'
    | '/documents/library/'
    | '/projects/$projectId/'
    | '/projects/$projectId/board/$taskId'
    | '/projects/$projectId/issues/$taskId'
    | '/projects/$projectId/documents/$documentId/modal'
    | '/projects/$projectId/storage/$fileId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/accounting/budgets'
    | '/accounting/transactions'
    | '/chat/$sessionId'
    | '/documents/new'
    | '/projects/recovery'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/business'
    | '/settings/community'
    | '/settings/integrations'
    | '/settings/labels'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/usage'
    | '/storage/$folderId'
    | '/view/$token'
    | '/accounting'
    | '/calendar'
    | '/chat'
    | '/contacts'
    | '/documents'
    | '/projects'
    | '/settings'
    | '/storage'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/promote'
    | '/documents/library/business'
    | '/documents/library/packages'
    | '/documents/library/templates'
    | '/projects/$projectId/board'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/table'
    | '/storage/$folderId/$fileId'
    | '/contacts/$contactId'
    | '/documents/$documentId'
    | '/documents/library'
    | '/projects/$projectId'
    | '/projects/$projectId/board/$taskId'
    | '/projects/$projectId/issues/$taskId'
    | '/projects/$projectId/documents/$documentId/modal'
    | '/projects/$projectId/storage/$fileId/modal'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_guest'
    | '/_app/contacts'
    | '/_app/documents'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/storage'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/contacts/$contactId'
    | '/_app/documents/$documentId'
    | '/_app/documents/library'
    | '/_app/projects/$projectId'
    | '/_app/accounting/budgets'
    | '/_app/accounting/transactions'
    | '/_app/chat/$sessionId'
    | '/_app/documents/new'
    | '/_app/projects/recovery'
    | '/_app/settings/ai'
    | '/_app/settings/appearance'
    | '/_app/settings/billing'
    | '/_app/settings/business'
    | '/_app/settings/community'
    | '/_app/settings/integrations'
    | '/_app/settings/labels'
    | '/_app/settings/notifications'
    | '/_app/settings/privacy'
    | '/_app/settings/profile'
    | '/_app/settings/usage'
    | '/_app/storage/$folderId'
    | '/_guest/view/$token'
    | '/_app/accounting/'
    | '/_app/calendar/'
    | '/_app/chat/'
    | '/_app/contacts/'
    | '/_app/documents/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/storage/'
    | '/_app/documents/$documentId/edit'
    | '/_app/documents/$documentId/promote'
    | '/_app/documents/library/business'
    | '/_app/documents/library/packages'
    | '/_app/documents/library/templates'
    | '/_app/projects/$projectId/board'
    | '/_app/projects/$projectId/issues'
    | '/_app/projects/$projectId/overview'
    | '/_app/projects/$projectId/reports'
    | '/_app/projects/$projectId/table'
    | '/_app/storage/$folderId/$fileId'
    | '/_app/contacts/$contactId/'
    | '/_app/documents/$documentId/'
    | '/_app/documents/library/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/board/$taskId'
    | '/_app/projects/$projectId/issues/$taskId'
    | '/_app/projects/$projectId/documents/$documentId/modal'
    | '/_app/projects/$projectId/storage/$fileId/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/storage/': {
      id: '/_app/storage/'
      path: '/'
      fullPath: '/storage/'
      preLoaderRoute: typeof AppStorageIndexRouteImport
      parentRoute: typeof AppStorageRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRouteRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_guest/view/$token': {
      id: '/_guest/view/$token'
      path: '/view/$token'
      fullPath: '/view/$token'
      preLoaderRoute: typeof GuestViewTokenRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_app/storage/$folderId': {
      id: '/_app/storage/$folderId'
      path: '/$folderId'
      fullPath: '/storage/$folderId'
      preLoaderRoute: typeof AppStorageFolderIdRouteImport
      parentRoute: typeof AppStorageRouteRoute
    }
    '/_app/settings/usage': {
      id: '/_app/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AppSettingsUsageRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/labels': {
      id: '/_app/settings/labels'
      path: '/labels'
      fullPath: '/settings/labels'
      preLoaderRoute: typeof AppSettingsLabelsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/community': {
      id: '/_app/settings/community'
      path: '/community'
      fullPath: '/settings/community'
      preLoaderRoute: typeof AppSettingsCommunityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/business': {
      id: '/_app/settings/business'
      path: '/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AppSettingsBusinessRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/projects/recovery': {
      id: '/_app/projects/recovery'
      path: '/recovery'
      fullPath: '/projects/recovery'
      preLoaderRoute: typeof AppProjectsRecoveryRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/_app/chat/$sessionId': {
      id: '/_app/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AppChatSessionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounting/transactions': {
      id: '/_app/accounting/transactions'
      path: '/accounting/transactions'
      fullPath: '/accounting/transactions'
      preLoaderRoute: typeof AppAccountingTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounting/budgets': {
      id: '/_app/accounting/budgets'
      path: '/accounting/budgets'
      fullPath: '/accounting/budgets'
      preLoaderRoute: typeof AppAccountingBudgetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/_app/documents/library': {
      id: '/_app/documents/library'
      path: '/library'
      fullPath: '/documents/library'
      preLoaderRoute: typeof AppDocumentsLibraryRouteRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/_app/documents/$documentId': {
      id: '/_app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteRouteImport
      parentRoute: typeof AppContactsRouteRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/documents/library/': {
      id: '/_app/documents/library/'
      path: '/'
      fullPath: '/documents/library/'
      preLoaderRoute: typeof AppDocumentsLibraryIndexRouteImport
      parentRoute: typeof AppDocumentsLibraryRouteRoute
    }
    '/_app/documents/$documentId/': {
      id: '/_app/documents/$documentId/'
      path: '/'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof AppDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AppDocumentsDocumentIdRouteRoute
    }
    '/_app/contacts/$contactId/': {
      id: '/_app/contacts/$contactId/'
      path: '/'
      fullPath: '/contacts/$contactId/'
      preLoaderRoute: typeof AppContactsContactIdIndexRouteImport
      parentRoute: typeof AppContactsContactIdRouteRoute
    }
    '/_app/storage/$folderId/$fileId': {
      id: '/_app/storage/$folderId/$fileId'
      path: '/$fileId'
      fullPath: '/storage/$folderId/$fileId'
      preLoaderRoute: typeof AppStorageFolderIdFileIdRouteImport
      parentRoute: typeof AppStorageFolderIdRoute
    }
    '/_app/projects/$projectId/table': {
      id: '/_app/projects/$projectId/table'
      path: '/table'
      fullPath: '/projects/$projectId/table'
      preLoaderRoute: typeof AppProjectsProjectIdTableRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/reports': {
      id: '/_app/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof AppProjectsProjectIdReportsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/overview': {
      id: '/_app/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof AppProjectsProjectIdOverviewRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/issues': {
      id: '/_app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/board': {
      id: '/_app/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof AppProjectsProjectIdBoardRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/documents/library/templates': {
      id: '/_app/documents/library/templates'
      path: '/templates'
      fullPath: '/documents/library/templates'
      preLoaderRoute: typeof AppDocumentsLibraryTemplatesRouteImport
      parentRoute: typeof AppDocumentsLibraryRouteRoute
    }
    '/_app/documents/library/packages': {
      id: '/_app/documents/library/packages'
      path: '/packages'
      fullPath: '/documents/library/packages'
      preLoaderRoute: typeof AppDocumentsLibraryPackagesRouteImport
      parentRoute: typeof AppDocumentsLibraryRouteRoute
    }
    '/_app/documents/library/business': {
      id: '/_app/documents/library/business'
      path: '/business'
      fullPath: '/documents/library/business'
      preLoaderRoute: typeof AppDocumentsLibraryBusinessRouteImport
      parentRoute: typeof AppDocumentsLibraryRouteRoute
    }
    '/_app/documents/$documentId/promote': {
      id: '/_app/documents/$documentId/promote'
      path: '/promote'
      fullPath: '/documents/$documentId/promote'
      preLoaderRoute: typeof AppDocumentsDocumentIdPromoteRouteImport
      parentRoute: typeof AppDocumentsDocumentIdRouteRoute
    }
    '/_app/documents/$documentId/edit': {
      id: '/_app/documents/$documentId/edit'
      path: '/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof AppDocumentsDocumentIdEditRouteImport
      parentRoute: typeof AppDocumentsDocumentIdRouteRoute
    }
    '/_app/projects/$projectId/issues/$taskId': {
      id: '/_app/projects/$projectId/issues/$taskId'
      path: '/$taskId'
      fullPath: '/projects/$projectId/issues/$taskId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesTaskIdRouteImport
      parentRoute: typeof AppProjectsProjectIdIssuesRoute
    }
    '/_app/projects/$projectId/board/$taskId': {
      id: '/_app/projects/$projectId/board/$taskId'
      path: '/$taskId'
      fullPath: '/projects/$projectId/board/$taskId'
      preLoaderRoute: typeof AppProjectsProjectIdBoardTaskIdRouteImport
      parentRoute: typeof AppProjectsProjectIdBoardRoute
    }
    '/_app/projects/$projectId/storage/$fileId/modal': {
      id: '/_app/projects/$projectId/storage/$fileId/modal'
      path: '/storage/$fileId/modal'
      fullPath: '/projects/$projectId/storage/$fileId/modal'
      preLoaderRoute: typeof AppProjectsProjectIdStorageFileIdModalRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/documents/$documentId/modal': {
      id: '/_app/projects/$projectId/documents/$documentId/modal'
      path: '/documents/$documentId/modal'
      fullPath: '/projects/$projectId/documents/$documentId/modal'
      preLoaderRoute: typeof AppProjectsProjectIdDocumentsDocumentIdModalRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface AppContactsContactIdRouteRouteChildren {
  AppContactsContactIdIndexRoute: typeof AppContactsContactIdIndexRoute
}

const AppContactsContactIdRouteRouteChildren: AppContactsContactIdRouteRouteChildren =
  {
    AppContactsContactIdIndexRoute: AppContactsContactIdIndexRoute,
  }

const AppContactsContactIdRouteRouteWithChildren =
  AppContactsContactIdRouteRoute._addFileChildren(
    AppContactsContactIdRouteRouteChildren,
  )

interface AppContactsRouteRouteChildren {
  AppContactsContactIdRouteRoute: typeof AppContactsContactIdRouteRouteWithChildren
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteRouteChildren: AppContactsRouteRouteChildren = {
  AppContactsContactIdRouteRoute: AppContactsContactIdRouteRouteWithChildren,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteRouteWithChildren =
  AppContactsRouteRoute._addFileChildren(AppContactsRouteRouteChildren)

interface AppDocumentsDocumentIdRouteRouteChildren {
  AppDocumentsDocumentIdEditRoute: typeof AppDocumentsDocumentIdEditRoute
  AppDocumentsDocumentIdPromoteRoute: typeof AppDocumentsDocumentIdPromoteRoute
  AppDocumentsDocumentIdIndexRoute: typeof AppDocumentsDocumentIdIndexRoute
}

const AppDocumentsDocumentIdRouteRouteChildren: AppDocumentsDocumentIdRouteRouteChildren =
  {
    AppDocumentsDocumentIdEditRoute: AppDocumentsDocumentIdEditRoute,
    AppDocumentsDocumentIdPromoteRoute: AppDocumentsDocumentIdPromoteRoute,
    AppDocumentsDocumentIdIndexRoute: AppDocumentsDocumentIdIndexRoute,
  }

const AppDocumentsDocumentIdRouteRouteWithChildren =
  AppDocumentsDocumentIdRouteRoute._addFileChildren(
    AppDocumentsDocumentIdRouteRouteChildren,
  )

interface AppDocumentsLibraryRouteRouteChildren {
  AppDocumentsLibraryBusinessRoute: typeof AppDocumentsLibraryBusinessRoute
  AppDocumentsLibraryPackagesRoute: typeof AppDocumentsLibraryPackagesRoute
  AppDocumentsLibraryTemplatesRoute: typeof AppDocumentsLibraryTemplatesRoute
  AppDocumentsLibraryIndexRoute: typeof AppDocumentsLibraryIndexRoute
}

const AppDocumentsLibraryRouteRouteChildren: AppDocumentsLibraryRouteRouteChildren =
  {
    AppDocumentsLibraryBusinessRoute: AppDocumentsLibraryBusinessRoute,
    AppDocumentsLibraryPackagesRoute: AppDocumentsLibraryPackagesRoute,
    AppDocumentsLibraryTemplatesRoute: AppDocumentsLibraryTemplatesRoute,
    AppDocumentsLibraryIndexRoute: AppDocumentsLibraryIndexRoute,
  }

const AppDocumentsLibraryRouteRouteWithChildren =
  AppDocumentsLibraryRouteRoute._addFileChildren(
    AppDocumentsLibraryRouteRouteChildren,
  )

interface AppDocumentsRouteRouteChildren {
  AppDocumentsDocumentIdRouteRoute: typeof AppDocumentsDocumentIdRouteRouteWithChildren
  AppDocumentsLibraryRouteRoute: typeof AppDocumentsLibraryRouteRouteWithChildren
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteRouteChildren: AppDocumentsRouteRouteChildren = {
  AppDocumentsDocumentIdRouteRoute:
    AppDocumentsDocumentIdRouteRouteWithChildren,
  AppDocumentsLibraryRouteRoute: AppDocumentsLibraryRouteRouteWithChildren,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteRouteWithChildren =
  AppDocumentsRouteRoute._addFileChildren(AppDocumentsRouteRouteChildren)

interface AppProjectsProjectIdBoardRouteChildren {
  AppProjectsProjectIdBoardTaskIdRoute: typeof AppProjectsProjectIdBoardTaskIdRoute
}

const AppProjectsProjectIdBoardRouteChildren: AppProjectsProjectIdBoardRouteChildren =
  {
    AppProjectsProjectIdBoardTaskIdRoute: AppProjectsProjectIdBoardTaskIdRoute,
  }

const AppProjectsProjectIdBoardRouteWithChildren =
  AppProjectsProjectIdBoardRoute._addFileChildren(
    AppProjectsProjectIdBoardRouteChildren,
  )

interface AppProjectsProjectIdIssuesRouteChildren {
  AppProjectsProjectIdIssuesTaskIdRoute: typeof AppProjectsProjectIdIssuesTaskIdRoute
}

const AppProjectsProjectIdIssuesRouteChildren: AppProjectsProjectIdIssuesRouteChildren =
  {
    AppProjectsProjectIdIssuesTaskIdRoute:
      AppProjectsProjectIdIssuesTaskIdRoute,
  }

const AppProjectsProjectIdIssuesRouteWithChildren =
  AppProjectsProjectIdIssuesRoute._addFileChildren(
    AppProjectsProjectIdIssuesRouteChildren,
  )

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdBoardRoute: typeof AppProjectsProjectIdBoardRouteWithChildren
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRouteWithChildren
  AppProjectsProjectIdOverviewRoute: typeof AppProjectsProjectIdOverviewRoute
  AppProjectsProjectIdReportsRoute: typeof AppProjectsProjectIdReportsRoute
  AppProjectsProjectIdTableRoute: typeof AppProjectsProjectIdTableRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdDocumentsDocumentIdModalRoute: typeof AppProjectsProjectIdDocumentsDocumentIdModalRoute
  AppProjectsProjectIdStorageFileIdModalRoute: typeof AppProjectsProjectIdStorageFileIdModalRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdBoardRoute: AppProjectsProjectIdBoardRouteWithChildren,
    AppProjectsProjectIdIssuesRoute:
      AppProjectsProjectIdIssuesRouteWithChildren,
    AppProjectsProjectIdOverviewRoute: AppProjectsProjectIdOverviewRoute,
    AppProjectsProjectIdReportsRoute: AppProjectsProjectIdReportsRoute,
    AppProjectsProjectIdTableRoute: AppProjectsProjectIdTableRoute,
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
    AppProjectsProjectIdDocumentsDocumentIdModalRoute:
      AppProjectsProjectIdDocumentsDocumentIdModalRoute,
    AppProjectsProjectIdStorageFileIdModalRoute:
      AppProjectsProjectIdStorageFileIdModalRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppProjectsRouteRouteChildren {
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppProjectsRecoveryRoute: typeof AppProjectsRecoveryRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteRouteChildren: AppProjectsRouteRouteChildren = {
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppProjectsRecoveryRoute: AppProjectsRecoveryRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteRouteWithChildren =
  AppProjectsRouteRoute._addFileChildren(AppProjectsRouteRouteChildren)

interface AppSettingsRouteRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsBusinessRoute: typeof AppSettingsBusinessRoute
  AppSettingsCommunityRoute: typeof AppSettingsCommunityRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsLabelsRoute: typeof AppSettingsLabelsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsUsageRoute: typeof AppSettingsUsageRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsBusinessRoute: AppSettingsBusinessRoute,
  AppSettingsCommunityRoute: AppSettingsCommunityRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsLabelsRoute: AppSettingsLabelsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsUsageRoute: AppSettingsUsageRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppStorageFolderIdRouteChildren {
  AppStorageFolderIdFileIdRoute: typeof AppStorageFolderIdFileIdRoute
}

const AppStorageFolderIdRouteChildren: AppStorageFolderIdRouteChildren = {
  AppStorageFolderIdFileIdRoute: AppStorageFolderIdFileIdRoute,
}

const AppStorageFolderIdRouteWithChildren =
  AppStorageFolderIdRoute._addFileChildren(AppStorageFolderIdRouteChildren)

interface AppStorageRouteRouteChildren {
  AppStorageFolderIdRoute: typeof AppStorageFolderIdRouteWithChildren
  AppStorageIndexRoute: typeof AppStorageIndexRoute
}

const AppStorageRouteRouteChildren: AppStorageRouteRouteChildren = {
  AppStorageFolderIdRoute: AppStorageFolderIdRouteWithChildren,
  AppStorageIndexRoute: AppStorageIndexRoute,
}

const AppStorageRouteRouteWithChildren = AppStorageRouteRoute._addFileChildren(
  AppStorageRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppContactsRouteRoute: typeof AppContactsRouteRouteWithChildren
  AppDocumentsRouteRoute: typeof AppDocumentsRouteRouteWithChildren
  AppProjectsRouteRoute: typeof AppProjectsRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppStorageRouteRoute: typeof AppStorageRouteRouteWithChildren
  AppAccountingBudgetsRoute: typeof AppAccountingBudgetsRoute
  AppAccountingTransactionsRoute: typeof AppAccountingTransactionsRoute
  AppChatSessionIdRoute: typeof AppChatSessionIdRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppContactsRouteRoute: AppContactsRouteRouteWithChildren,
  AppDocumentsRouteRoute: AppDocumentsRouteRouteWithChildren,
  AppProjectsRouteRoute: AppProjectsRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppStorageRouteRoute: AppStorageRouteRouteWithChildren,
  AppAccountingBudgetsRoute: AppAccountingBudgetsRoute,
  AppAccountingTransactionsRoute: AppAccountingTransactionsRoute,
  AppChatSessionIdRoute: AppChatSessionIdRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestViewTokenRoute: typeof GuestViewTokenRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestViewTokenRoute: GuestViewTokenRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
