export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Archive,
  ArrowArcLeft as ArchiveRestore,
  ArrowDown,
  ArrowsDownUp as ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ArrowsIn,
  ArrowsOut,
  ArrowSquareOut as ExternalLink,
  SealCheck as BadgeCheck,
  Bell,
  CurrencyBtc as Bitcoin,
  BookOpen,
  House as Home,
  Bookmark,
  Bug,
  Calendar,
  Calendar as CalendarIcon,
  CalendarDots as CalendarDays,
  Camera,
  Check,
  Clock,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUp,
  CaretDoubleLeft as ChevronsLeft,
  CaretDoubleRight as ChevronsRight,
  CaretUpDown as ChevronsUpDown,
  CaretUpDown as ChevronsUpDownIcon,
  Circle,
  CheckCircle as CircleCheck,
  CircleDashed,
  Record as CircleDot,
  XCircle as CircleX,
  Confetti,
  Copy,
  CreditCard,
  CurrencyDollar as DollarSign,
  Download,
  DotsThree as Ellipsis,
  Eye,
  EyeClosed as EyeOff,
  File,
  FileImage,
  Signature as FileSignature,
  MicrosoftExcelLogo as FileSpreadsheet,
  FileText,
  FileText as FileTextIcon,
  FileVideo,
  Flame,
  Flag,
  Folder,
  FolderPlus as FolderInput,
  Kanban as FolderKanban,
  FolderOpen,
  Gift,
  GitMerge,
  Globe,
  DotsSixVertical as GripVertical,
  HardDrive,
  IdentificationCard as IdCard,
  Image as ImageIcon,
  Info,
  KeyReturn,
  Kanban,
  Bank as Landmark,
  Stack as Layers,
  Lightbulb,
  GridFour as LayoutGrid,
  House,
  Link,
  Link as LinkIcon,
  LinkSimple as Link2,
  List,
  Funnel as ListFilter,
  ListBullets,
  SpinnerGap as Loader2,
  SignOut as LogOut,
  EnvelopeSimple as Mail,
  ChatCircle as MessageSquare,
  Microphone as Mic,
  Minus,
  Money,
  Moon,
  DotsThree as MoreHorizontal,
  Package,
  Palette,
  SidebarSimple as PanelLeft,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  SidebarSimple as PanelRight,
  Paperclip,
  PencilSimple as Pencil,
  Phone,
  PushPin as Pin,
  PushPinSlash as PinOff,
  Plus,
  PlusCircle,
  PuzzlePiece as Puzzle,
  QrCode,
  Question as CircleHelp,
  Receipt,
  Repeat,
  ArrowCounterClockwise as RotateCcw,
  ArrowClockwise as RotateCw,
  FloppyDisk as Save,
  Scroll as ScrollText,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Sliders as Settings2,
  Shield,
  Smiley as Smile,
  NotePencil as SquarePen,
  Sparkle,
  Star,
  Stop,
  Sun,
  Table as Table2,
  Tag,
  TextT as Text,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Warning as TriangleAlert,
  StripeLogo as Stripe,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  Wallet as WalletIcon,
  X,
  XCircle,
  Lightning as Zap,
} from '@phosphor-icons/react'
