export const queryKeys = {
  user: ['user'] as const,
  getStarted: ['user', 'get-started'] as const,
  projects: ['projects'] as const,
  trashedProjects: ['projects', 'trash'] as const,
  contacts: ['contacts'] as const,
  transactions: ['transactions'] as const,
  transactionsList: (filters: Record<string, unknown>) =>
    ['transactions', 'list', filters] as const,
  revenueRecord: ['transactions', 'revenue-record'] as const,
  transaction: (id: string) => ['transactions', id] as const,
  storageFiles: ['storage', 'files'] as const,
  storageTrashedFiles: ['storage', 'trash'] as const,
  storageFolders: ['storage', 'folders'] as const,
  storageQuota: ['storage', 'quota'] as const,
  documents: ['documents'] as const,
  documentsList: (filters: Record<string, unknown>) => ['documents', 'list', filters] as const,
  document: (id: string) => ['documents', id] as const,
  documentVersions: (id: string) => ['document-versions', id] as const,
  contactActivity: (contactId: string, filters?: { entityType?: string }) =>
    ['activity', 'contact', contactId, filters] as const,
  senderProfiles: ['business', 'senderProfiles'] as const,
  senderProfilesOrder: ['business', 'senderProfiles', 'order'] as const,
  remarkTemplates: ['business', 'remarkTemplates'] as const,
  remarkTemplatesOrder: ['business', 'remarkTemplates', 'order'] as const,
  budgets: ['budgets'] as const,
  wallets: ['wallets'] as const,
  accountingChart: ['accounting', 'chart-data'] as const,
  accountingSummary: (period: string) => ['accounting', 'summary', period] as const,
  accountingForecast: ['accounting', 'forecast'] as const,
  chatSessions: ['chatSessions'] as const,
  notifications: ['notifications'] as const,
  guestDocument: (token: string) => ['guest-document', token] as const,
  itemTemplates: ['item-templates'] as const,
  itemTemplateGroups: ['item-template-groups'] as const,
  projectDocuments: (projectId: string) => ['project-documents', projectId] as const,
  projectMilestones: (projectId: string) => ['project-milestones', projectId] as const,
  projectCashflow: (projectId: string) => ['project-cashflow', projectId] as const,
  labels: ['labels'] as const,
  calendarEvents: (range: { start: string; end: string }) =>
    ['calendar-events', range.start, range.end] as const,
  calendarOverlays: (range: { start: string; end: string }) =>
    ['calendar-overlays', range.start, range.end] as const,
  calendarConnection: ['calendar-connection'] as const,
  googleCalendars: ['google-calendars'] as const,
  contactBriefing: (contactId: string) => ['contacts', contactId, 'briefing'] as const,
  linkedAccounts: ['linked-accounts'] as const,
  lineConnection: ['line-connection'] as const,
}
